on:
  issues: 
    types:
      - opened

jobs:
  test-job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - uses: actions/checkout@v4
    
    - uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        labels: '["kode-kloud","bugs"]'