on:
    issues: 
          types:
           - opened
           - labeled
jobs:
    test:
      runs-on: ubuntu-latest
    #   permissions:
    #     issues: write
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test just output the message
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["kk","kkkkkk"]'