on:
    issues: 
          types:
           - opened

jobs:
    test:
      runs-on: ubuntu-latest
      permissions:
        issues: write
      steps:
      - uses: actions/checkout@v2
      
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["kode-kloud","bugs"]'